<a href="https://colab.research.google.com/github/ArifQureshi3966/MLAssignment/blob/main/Introduction_to_Machine_Learningl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Assignmnet 1**


**Arif Ullah Qureshi**

**2017-EE-145**

**Section D**

# **Introduction**
In this machine learning assignmnet I will be using the Car Evaluation Data Set from the UCI Machine Learning Repository .I will shuffle the dateset to create 3 splits of equal ratio.I will use Random Forest Classifier and Decison Tree Classifier to try to predict car acceptibility using a number of features.After training and testing of the 3 splits.I will use their average accuracy of the 2 models to determine with model is the best.


#Mouting Drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


#Libraries Initialization


Initializing the necessary Python libraries.I will be using Python to solve a binary classification problem using both a decision tree as well as a random forest.

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn import ensemble, preprocessing, model_selection
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

#Importing the dataset

I will be using the Car Evaluation Data Set from the UCI Machine Learning Repository .I get a count of the number of unique values for each feature column in the DataFrame.

In [ ]:
dataFrame  = pd.read_csv('/content/drive/MyDrive/ML Assignmnet/Dataset/car_evaluation.csv',header=0)
dataFrame .info()

# Get a count of the number of unique values for each feature column in the DataFrame.
feature_names = list(dataFrame.columns.values[:-1])
for feature in feature_names:
    unique_count = dataFrame[feature].nunique()
    unique_vals = dataFrame[feature].unique()
    print("{}: {} values, {}".format(feature, unique_count, unique_vals))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB
buying: 4 values, ['vhigh' 'high' 'med' 'low']
maint: 4 values, ['vhigh' 'high' 'med' 'low']
doors: 4 values, ['2' '3' '4' '5more']
persons: 3 values, ['2' '4' 'more']
lug_boot: 3 values, ['small' 'med' 'big']
safety: 3 values, ['low' 'med' 'high']


#Encoding

The data as obtained from the UCI dataset repository have
to be cleaned and to ensure that it is in the standard quality
before the model creation is initiated. The data cleaning
conducted on the dataset is the conversion of nominal attributes to numeric attributes. The nominal to numeric conversion process was conducted in order to make the process of normalization possible.

### Mapping

In [ ]:
buyingMapping = {"low": 1, "med": 2, "high": 3, "vhigh": 4}
dataFrame["buying"] = dataFrame["buying"].map(buyingMapping)

maintMapping = {"low": 1, "med": 2, "high": 3, "vhigh": 4}
dataFrame["maint"] = dataFrame["maint"].map(maintMapping)

doorsMapping = {"2": 2, "3": 3, "4": 4, "5more": 5}
dataFrame["doors"] = dataFrame["doors"].map(doorsMapping)

personsMapping = {"2": 2, "4": 4, "more": 6}
dataFrame["persons"] = dataFrame["persons"].map(personsMapping)

lugBootMapping = {"small": 1, "med": 2, "big": 3}
dataFrame["lug_boot"] = dataFrame["lug_boot"].map(lugBootMapping)

safetyMapping = {"low": 1, "med": 2, "high": 3}
dataFrame["safety"] = dataFrame["safety"].map(safetyMapping)

classMapping = {"unacc": 0, "acc": 1, "good": 2, "vgood": 3}
dataFrame["class"] = dataFrame["class"].map(classMapping)
dataFrame.tail()

buying  maint  doors  persons  lug_boot  safety  class
1723       1      1      5        6         2       2      2
1724       1      1      5        6         2       3      3
1725       1      1      5        6         3       1      0
1726       1      1      5        6         3       2      2
1727       1      1      5        6         3       3      3

# Traning

Training of Random Forest and Decision tree models.


Assigning the columns in the DataFrame to the features 'X' (independent variables) and labels 'y' (dependent variable).

In [ ]:
# Features.
X = dataFrame.loc[:, 'buying':'safety']
# Labels.
y = dataFrame.loc[:, 'class']

Spliting the dataset in an 70:30 ratio for training and test set respectively for 3 different random states to create 3 different datasets.
1. Split 1
2. Split 2
3. Split 3

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
X_train2, X_test2, y_train2, y_test2 = model_selection.train_test_split(X,y,test_size=0.3,random_state=0)

In [ ]:
X_train3, X_test3, y_train3, y_test3 = model_selection.train_test_split(X,y,test_size=0.3,random_state=21)

## Random Forest


I will be using a random forest classifier, which is an ensemble of individial decision tree classifiers.

Creating the Random forest classifier using 500 decision trees.Each decision tree created by the random forest classifier algorithm trains on a random sample from the data and on random features. The algorithm takes the classifications made by each of these trees, and the one with most votes is the final prediction of the random forest algorithm. This ensemble approach improves the accuracy of the final overall classification and helps minimise the chances of an overfitted model.The random forest algorithm is fast, can work with large datasets and maintains its accuracy despite missing data, but unlike a single decision tree it is difficult to interpret.

##### Random Forest for Split 1

In [ ]:
Rclf = RandomForestClassifier(n_estimators=500, random_state=42)
# Training the classifier. This is where the forest of decision trees are created.
Rclf.fit(X_train, y_train)
A1 = Rclf.score(X_test,y_test)
y_pred = Rclf.predict(X_test)
print("Accuracy for split 1 using random forest is: {0:0.4f} ".format(A1*100),"%")
scaler = preprocessing.MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test)
Rclf.fit(X_train_scaled,y_train)
AS1 = Rclf.score(X_test_scaled,y_test)
print("Accuracy for split 1 using random forest when data is scaled between the maximum and minimum: {0:0.4f} ".format(AS1*100),"%")

Accuracy for split 1 using random forest is: 96.5318  %
Accuracy for split 1 using random forest when data is scaled between the maximum and minimum: 96.3391  %


##### Random Forest for Split 2

In [ ]:
Rclf2 = RandomForestClassifier(n_estimators=500, random_state=0)
# Training the classifier. This is where the forest of decision trees are created.
Rclf2.fit(X_train2, y_train2)
A2 = Rclf2.score(X_test2,y_test2)
y_pred2 = Rclf2.predict(X_test2)
print("Accuracy for split 2 using random forest is: {0:0.4f} ".format(A2*100),"%")
scaler2 = preprocessing.MinMaxScaler()
X_train_scaled2 = scaler2.fit_transform(X_train2)
X_test_scaled2 = scaler2.fit_transform(X_test2)
Rclf2.fit(X_train_scaled2,y_train2)
AS2 = Rclf2.score(X_test_scaled2,y_test2)
print("Accuracy for split 2 using random forest when data is scaled between the maximum and minimum: {0:0.4f} ".format(AS2*100),"%")

Accuracy for split 2 using random forest is: 98.0732  %
Accuracy for split 2 using random forest when data is scaled between the maximum and minimum: 98.0732  %


##### Random Forest for Split 3

In [ ]:
Rclf3 = RandomForestClassifier(n_estimators=500, random_state=21)
# Training the classifier. This is where the forest of decision trees are created.
Rclf3.fit(X_train3, y_train3)
A3 = Rclf3.score(X_test3,y_test3)
y_pred3 = Rclf3.predict(X_test3)
print("Accuracy for split 3 using random forest is: {0:0.4f} ".format(A3*100),"%")
scaler3 = preprocessing.MinMaxScaler()
X_train_scaled3 = scaler3.fit_transform(X_train3)
X_test_scaled3 = scaler3.fit_transform(X_test3)
Rclf3.fit(X_train_scaled3,y_train3)
AS3 = Rclf3.score(X_test_scaled3,y_test3)
print("Accuracy for split 3 using random forest when data is scaled between the maximum and minimum: {0:0.4f} ".format(AS3*100),"%")

Accuracy for split 3 using random forest is: 97.6879  %
Accuracy for split 3 using random forest when data is scaled between the maximum and minimum: 97.8805  %


## Decision Tree

A decision tree is a simple tree-like structure constituting nodes and branches.At each step, a decision is made based on the attribute in question, and the result generates a branch of the tree. Using this divide and conquer classification rules are generated. The rule is a path from the Root node to an End node. An advantage of Decision Tree is that the Information gained can be used in feature selection as well.

##### Decision Tree for Split 1

In [ ]:
Dtree1 = DecisionTreeClassifier(criterion = 'entropy', random_state=42).fit(X_train,y_train)
y_predic1 = Dtree1.predict(X_test)
AD1 = Dtree1.score(X_test,y_test)
print("Accuracy for split 1 using Decision Trees is: {0:0.4f} ".format(AD1*100),"%")

Accuracy for split 1 using Decision Trees is: 96.9171  %


##### Decision Tree for Split 2

In [ ]:
Dtree2 = DecisionTreeClassifier(criterion = 'entropy', random_state=0).fit(X_train2,y_train2)
y_predic2 = Dtree2.predict(X_test2)
AD2 = Dtree2.score(X_test2,y_test2)
print("Accuracy for split 2 using Decision Trees is: {0:0.4f} ".format(AD2*100),"%")

Accuracy for split 2 using Decision Trees is: 98.2659  %


##### Decision Tree for Split 3

In [ ]:
Dtree3 = DecisionTreeClassifier(criterion = 'entropy',random_state=21).fit(X_train3,y_train3)
y_predic3 = Dtree3.predict(X_test3)
AD3 = Dtree3.score(X_test3,y_test3)
print("Accuracy for split 3 using Decision Trees is: {0:0.4f} ".format(AD3*100),"%")

Accuracy for split 3 using Decision Trees is: 96.7245  %


# Average Accuracy

### Average Accuracy of Random Forest

In [ ]:
Avg_Acc1 = (A1+A2+A3)/3
print('Average accuracy using Random Forest : {0:0.4f}'. format(Avg_Acc1*100),"%")

Average accuracy using Random Forest : 97.4310 %


### Average Accuracy of Decision Tree

In [ ]:
Avg_Acc = (AD1+AD2+AD3)/3
print('Average accuracy using Decision Tree Classifier: {0:0.4f}'. format(Avg_Acc*100),"%")

Average accuracy using Decision Tree Classifier: 97.3025 %


Accuracy of the Random Forest Classifier is slightly greater than the Decision Tree Classifier.So Random Forest performs better for this dataset. 

# Confusion matrices and Classifcation Report
The Confusion-matrix yields the most ideal suite of metrics for evaluating the performance of a classification algorithm such as Decision tree  and Random Forest. A confusion matrix is a summary of prediction results on a classification problem.The number of correct and incorrect predictions are summarized with count values and broken down by each class. This is the key to the confusion matrix.

Given an array or list of expected values and a list of predictions from your machine learning model, the confusion_matrix() function will calculate a confusion matrix and return the result as an array

## Using Random Forests

##### Split 1 Confusion Matrix 

In [ ]:
cm1= confusion_matrix(y_test,y_pred)
print('Confusion matrix on split 1 using random forest \n\n', cm1)
print(classification_report(y_test, y_pred))

Confusion matrix on split 1 using random forest 

 [[355   3   0   0]
 [  2 108   6   2]
 [  0   1  17   1]
 [  0   3   0  21]]
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       358
           1       0.94      0.92      0.93       118
           2       0.74      0.89      0.81        19
           3       0.88      0.88      0.88        24

    accuracy                           0.97       519
   macro avg       0.89      0.92      0.90       519
weighted avg       0.97      0.97      0.97       519



##### Split 2 Confusion Matrix 

In [ ]:
cm2=confusion_matrix(y_test2,y_pred2)
print('Confusion matrix on split 2 using random forest \n\n', cm2)
print(classification_report(y_test2, y_pred2))

Confusion matrix on split 2 using random forest 

 [[361   2   0   0]
 [  1 112   2   0]
 [  0   0  23   2]
 [  0   3   0  13]]
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       363
           1       0.96      0.97      0.97       115
           2       0.92      0.92      0.92        25
           3       0.87      0.81      0.84        16

    accuracy                           0.98       519
   macro avg       0.94      0.93      0.93       519
weighted avg       0.98      0.98      0.98       519



##### Split 3 Confusion Matrix 

In [ ]:
cm3=confusion_matrix(y_test3,y_pred3)
print('Confusion matrix on split 3 using random forest \n\n', cm3)
print(classification_report(y_test3, y_pred3))

Confusion matrix on split 3 using random forest 

 [[345   1   0   0]
 [  2 133   1   0]
 [  0   2  17   2]
 [  0   4   0  12]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       346
           1       0.95      0.98      0.96       136
           2       0.94      0.81      0.87        21
           3       0.86      0.75      0.80        16

    accuracy                           0.98       519
   macro avg       0.94      0.88      0.91       519
weighted avg       0.98      0.98      0.98       519



## Using Decision Trees

##### All Data Splits Confusion Matrices

In [ ]:
cm1dt = confusion_matrix(y_test, y_predic1)
cm2dt = confusion_matrix(y_test2, y_predic2)
cm3dt = confusion_matrix(y_test3, y_predic3)
print('Confusion matrix on split 1 using Decision Trees\n\n', cm1dt)
print(classification_report(y_test, y_predic1))
print('Confusion matrix on split 2 using Decision Trees\n\n', cm2dt)
print(classification_report(y_test2, y_predic2))
print('Confusion matrix on split 3 using Decision Trees\n\n', cm3dt)
print(classification_report(y_test3, y_predic3))

Confusion matrix on split 1 using Decision Trees

 [[358   0   0   0]
 [  3 109   5   1]
 [  0   1  17   1]
 [  0   3   2  19]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       358
           1       0.96      0.92      0.94       118
           2       0.71      0.89      0.79        19
           3       0.90      0.79      0.84        24

    accuracy                           0.97       519
   macro avg       0.89      0.90      0.89       519
weighted avg       0.97      0.97      0.97       519

Confusion matrix on split 2 using Decision Trees

 [[362   1   0   0]
 [  2 109   4   0]
 [  0   1  24   0]
 [  0   1   0  15]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00       363
           1       0.97      0.95      0.96       115
           2       0.86      0.96      0.91        25
           3       1.00      0.94      0.97        16

    accuracy                         

#Statistical analysis using TTest
Statistical Testing with Paired T-Test —  According to given dataset, I have only one dataset but I have used multiple folds of the same dataset to evaluate the accuracies.I need to use a test which can test the model’s accuracies on multiple folds of single datasets. The Paired T-Test would most suitable statistical test for this purpose.

For all the 3 folds, the accuracy difference is very very minute. This represents both models are performing almost the same. I need to use statistical testing to resolve this doubt.

We need a threshold, alpha to find out the statistical difference. Here’s the deal with the alpha.



*  If p > alpha - > then there's no significance difference between two models
*  If p < alpha -> then there is significance difference between two models




In [ ]:
import numpy as np
RF_model=np.array([A1,A2,A3])
DT_model=np.array([AD1,AD2,AD3])
print(np.var(RF_model),np.var(DT_model))
import scipy.stats as stats
stats.ttest_ind(a=RF_model,b=DT_model,equal_var=True)

4.289988363406576e-05 4.702487244503292e-05


Ttest_indResult(statistic=0.19156525704422148, pvalue=0.8574140036991883)

Since the difference between the accuracies is very very low, I need a greater alpha to find out the difference. So, alpha = 0.5, is significant to show the difference for my problem and since p > alpha so then there's no significance difference between two models.

# Conclusion

## Why Did Our Random Forest Model Outperform the Decision Tree?
Our decision tree model is overfitting on the training data.The decision tree model gives high importance to a particular set of features. But the random forest chooses features randomly during the training process. Therefore, it does not depend highly on any specific set of features.
Random Forest is suitable for situations when we have a large dataset, and interpretability is not a major concern.Therefore, the random forest can generalize over the data in a better way. This randomized feature selection makes random forest much more accurate than a decision tree.

Reference Link: [Link](https://www.analyticsvidhya.com/blog/2020/05/decision-tree-vs-random-forest-algorithm/#:~:text=Each%20node%20in%20the%20decision,to%20generate%20the%20final%20output.&text=The%20Random%20Forest%20Algorithm%20combines,to%20generate%20the%20final%20output.)

## Why Choose Random Forest and Not Decision Trees?

Random forest works well with non-linear data, has lower risk of overfitting,runs efficiently on a large dataset and also has Better accuracy than other classification algorithms.

While the decision tree are prone to overfitting.It can be quite large, thus making pruning necessary.It can’t guarantee optimal trees.It gives low prediction accuracy for a dataset as compared to other machine learning algorithms.Calculations can become complex when there are many class variables.

Reference Link: [Link](https://towardsai.net/p/machine-learning/why-choose-random-forest-and-not-decision-trees)